// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "start", "symbols": ["template"]},
    {"name": "start", "symbols": ["template", "__", "module"]},
    {"name": "linear", "symbols": ["__", "module"]},
    {"name": "linear", "symbols": []},
    {"name": "2Branches", "symbols": ["_", {"literal":"("}, "innerModule", {"literal":")"}, "_", {"literal":"("}, "innerModule", {"literal":")"}]},
    {"name": "3Branches", "symbols": ["_", {"literal":"("}, "innerModule", {"literal":")"}, "_", {"literal":"("}, "innerModule", {"literal":")"}, "_", {"literal":"("}, "innerModule", {"literal":")"}]},
    {"name": "innerModule", "symbols": ["_", "module", "_"]},
    {"name": "innerModule", "symbols": ["_"]},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ ]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"]},
    {"name": "__", "symbols": [{"literal":" "}]},
    {"name": "template$string$1", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"c"}, {"literal":"T"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "template", "symbols": ["template$string$1"]},
    {"name": "template$string$2", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"S"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"T"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "template", "symbols": ["template$string$2"]},
    {"name": "template$string$3", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"P"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"T"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "template", "symbols": ["template$string$3"]},
    {"name": "module$string$1", "symbols": [{"literal":"I"}, {"literal":"m"}, {"literal":"e"}, {"literal":"i"}, {"literal":"S"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$1", "linear"]},
    {"name": "module$string$2", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"i"}, {"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"S"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}, {"literal":"r"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$2", "linear"]},
    {"name": "module$string$3", "symbols": [{"literal":"A"}, {"literal":"s"}, {"literal":"y"}, {"literal":"n"}, {"literal":"c"}, {"literal":"T"}, {"literal":"a"}, {"literal":"s"}, {"literal":"k"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$3", "linear"]},
    {"name": "module$string$4", "symbols": [{"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"S"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"z"}, {"literal":"e"}, {"literal":"r"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$4", "linear"]},
    {"name": "module$string$5", "symbols": [{"literal":"B"}, {"literal":"l"}, {"literal":"u"}, {"literal":"e"}, {"literal":"t"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"D"}, {"literal":"e"}, {"literal":"t"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$5", "linear"]},
    {"name": "module$string$6", "symbols": [{"literal":"B"}, {"literal":"u"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}, {"literal":"C"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"b"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$6", "linear"]},
    {"name": "module$string$7", "symbols": [{"literal":"D"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$7", "linear"]},
    {"name": "module$string$8", "symbols": [{"literal":"I"}, {"literal":"c"}, {"literal":"c"}, {"literal":"G"}, {"literal":"l"}, {"literal":"o"}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"F"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$8", "linear"]},
    {"name": "module$string$9", "symbols": [{"literal":"L"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"C"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$9", "linear"]},
    {"name": "module$string$10", "symbols": [{"literal":"O"}, {"literal":"b"}, {"literal":"f"}, {"literal":"u"}, {"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"1"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$10", "linear"]},
    {"name": "module$string$11", "symbols": [{"literal":"O"}, {"literal":"b"}, {"literal":"f"}, {"literal":"u"}, {"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"2"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$11", "linear"]},
    {"name": "module$string$12", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"R"}, {"literal":"e"}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":"e"}, {"literal":"L"}, {"literal":"i"}, {"literal":"f"}, {"literal":"e"}, {"literal":"c"}, {"literal":"y"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$12", "linear"]},
    {"name": "module$string$13", "symbols": [{"literal":"P"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"A"}, {"literal":"p"}, {"literal":"i"}, {"literal":"P"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$13", "linear"]},
    {"name": "module$string$14", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"f"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"1"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$14", "linear"]},
    {"name": "module$string$15", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"f"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"M"}, {"literal":"e"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"d"}, {"literal":"1"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$15", "linear"]},
    {"name": "module$string$16", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"f"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"M"}, {"literal":"e"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"d"}, {"literal":"1"}, {"literal":"N"}, {"literal":"o"}, {"literal":"n"}, {"literal":"S"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$16", "linear"]},
    {"name": "module$string$17", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"I"}, {"literal":"c"}, {"literal":"c"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$17", "linear"]},
    {"name": "module$string$18", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"R"}, {"literal":"e"}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$18", "linear"]},
    {"name": "module$string$19", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"S"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"z"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$19", "linear"]},
    {"name": "module$string$20", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"U"}, {"literal":"n"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$20", "linear"]},
    {"name": "module$string$21", "symbols": [{"literal":"S"}, {"literal":"m"}, {"literal":"s"}, {"literal":"S"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$21", "linear"]},
    {"name": "module$string$22", "symbols": [{"literal":"I"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"t"}, {"literal":"S"}, {"literal":"m"}, {"literal":"s"}, {"literal":"S"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$22", "linear"]},
    {"name": "module$string$23", "symbols": [{"literal":"L"}, {"literal":"o"}, {"literal":"g"}, {"literal":"S"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$23", "linear"]},
    {"name": "module$string$24", "symbols": [{"literal":"L"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$24", "linear"]},
    {"name": "module$string$25", "symbols": [{"literal":"A"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"T"}, {"literal":"o"}, {"literal":"S"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$25", "linear"]},
    {"name": "module$string$26", "symbols": [{"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$26", "linear"]},
    {"name": "module$string$27", "symbols": [{"literal":"A"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"E"}, {"literal":"x"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$27", "linear"]},
    {"name": "module$string$28", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"B"}, {"literal":"u"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$28", "linear"]},
    {"name": "module$string$29", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"o"}, {"literal":"m"}, {"literal":"I"}, {"literal":"f"}, {"literal":"E"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}, {"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "module", "symbols": ["module$string$29", "2Branches"]}
]
  , ParserStart: "start"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
